# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysinfo', '0002_auto_20170704_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='name',
            field=models.CharField(default='anonymous', max_length=30, verbose_name='发表人名称'),
            preserve_default=False,
        ),
    ]
