# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 01:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sysinfo', '0004_auto_20170704_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-pub_date']},
        ),
    ]
